whitelist_rules: 
 # Find all the available rules by running: 
 # swiftlint rules
 
 - anyobject_protocol
 ##- array_init
 #- attributes
 - block_based_kvo
 - class_delegate_protocol
 - closing_brace
 - closure_end_indentation
 - closure_parameter_position
 - closure_spacing
 - colon
 - comma
 - compiler_protocol_init
 #- conditional_returns_on_newline
 - contains_over_first_not_nil
 - control_statement
 - convenience_type
 - custom_rules
 #- cyclomatic_complexity
 - discarded_notification_center_observer
 - discouraged_direct_init
 - discouraged_object_literal
 - discouraged_optional_boolean
 #- discouraged_optional_collection
 - dynamic_inline
 - empty_count
 - empty_enum_arguments
 - empty_parameters
 - empty_parentheses_with_trailing_closure
 - empty_string
 - empty_xctest_method
 #- explicit_acl
 #- explicit_enum_raw_value
 #- explicit_init
 #- explicit_top_level_acl
 #- explicit_type_interface
 - extension_access_modifier
 #- fallthrough
 - fatal_error_message
 #- file_header
 #- file_length
 ##- file_name
 #- first_where
 - for_where
 #- force_cast
 - force_try
 #- force_unwrapping
 #- function_body_length
 - function_default_parameter_at_end
 #- function_parameter_count
 - generic_type_name
 #- identifier_name
 - implicit_getter
 - implicit_return
 #- implicitly_unwrapped_optional
 - is_disjoint
 - joined_default_parameter
 - large_tuple
 - leading_whitespace
 - legacy_cggeometry_functions
 - legacy_constant
 - legacy_constructor
 - legacy_nsgeometry_functions
 - let_var_whitespace
 - line_length
 - literal_expression_end_indentation
 #- lower_acl_than_parent
 - mark
 ##- missing_docs
 - modifier_order
 - multiline_arguments
 ##- multiline_function_chains
 ##- multiline_parameters
 - multiple_closures_with_trailing_closure
 #- nesting
 - nimble_operator
 #- no_extension_access_modifier
 - no_fallthrough_only
 ##- no_grouping_extension
 - notification_center_detachment
 #- number_separator
 #- object_literal
 - opening_brace
 - operator_usage_whitespace
 - operator_whitespace
 #- overridden_super_call
 #- override_in_extension
 #- pattern_matching_keywords
 - prefixed_toplevel_constant
 - private_action
 - private_outlet
 #- private_over_fileprivate
 - private_unit_test
 - prohibited_super_call
 - protocol_property_accessors_order
 - quick_discouraged_call
 - quick_discouraged_focused_test
 - quick_discouraged_pending_test
 - redundant_discardable_let
 - redundant_nil_coalescing
 - redundant_optional_initialization
 - redundant_set_access_control
 - redundant_string_enum_value
 - redundant_type_annotation
 - redundant_void_return
 - required_enum_case
 - return_arrow_whitespace
 - shorthand_operator
 #- single_test_class
 - sorted_first_last
 - sorted_imports
 - statement_position
 #- strict_fileprivate
 - superfluous_disable_command
 - switch_case_alignment
 - switch_case_on_newline
 - syntactic_sugar
 #- todo
 #- trailing_closure
 - trailing_comma
 - trailing_newline
 - trailing_semicolon
 - trailing_whitespace
 #- type_body_length
 - type_name
 #- unavailable_function
 - unneeded_break_in_switch
 - unneeded_parentheses_in_closure_argument
 - untyped_error_in_catch
 - unused_closure_parameter
 - unused_enumerated
 #- unused_optional_binding
 - valid_ibinspectable
 - vertical_parameter_alignment
 - vertical_parameter_alignment_on_call
 - vertical_whitespace
 - void_return
 - weak_delegate
 - xctfail_message
 - yoda_condition

line_length:
  ignores_comments: true
  warning: 200
  error: 200
type_name:
  min_length: 3 # only warning
  max_length:   # warning and error
    warning: 50
    error: 50

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - Catty/Defines/LanguageTranslationDefinesSwift.swift
 - CattyUITests/Defines/LanguageTranslationDefinesUI.swift
 - CattyUISnapshots/Defines/LanguageTranslationDefinesUI.swift
 - CattyUISnapshots/Supporting Files/SnapshotHelper.swift
 - RunScripts/license-validator.swift
 - RunScripts/precompile-tests.swift
