whitelist_rules: 
 - trailing_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Catty/Defines/LanguageTranslationDefinesSwift.swift
 - CattyUITests/Defines/LanguageTranslationDefinesUI.swift
 - CattyUISnapshots/Helper/SnapshotHelper.swift
 - RunScripts/license-validator.swift
 - RunScripts/precompile-tests.swift
 