whitelist_rules: 
 - trailing_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - Catty/Defines/LanguageTranslationDefinesSwift.swift
 - Catty UITests/Defines/LanguageTranslationDefinesUI.swift
 - RunScripts/license-validator.swift
 - RunScripts/precompile-tests.swift
 