whitelist_rules: 
 - trailing_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - Catty/Defines/LanguageTranslationDefinesSwift.swift
 - license-validator.swift
 - precompile-tests.swift
 