whitelist_rules: 
 - trailing_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - BuildScripts
 - Carthage
 - Pods
 - Catty/Defines/LanguageTranslationDefinesSwift.swift
 