disabled_rules: 
 # Rule identifiers to exclude from running

 - force_cast
 - identifier_name
 - file_length
 - type_body_length
 - function_body_length
 - cyclomatic_complexity
 - function_parameter_count
 - nesting
 - unused_optional_binding

opt_in_rules: 
 # Some rules are only opt-in
 # Find all the available rules by running: 
 # swiftlint rules
 
 - anyobject_protocol
 - array_init
 #- attributes
 - closure_end_indentation
 - closure_spacing
 #- conditional_returns_on_newline
 - contains_over_first_not_nil
 - convenience_type
 - discouraged_object_literal
 - discouraged_optional_boolean
 #- discouraged_optional_collection
 - empty_count
 - empty_string
 - empty_xctest_method
 #- explicit_acl
 #- explicit_enum_raw_value
 #- explicit_init
 #- explicit_top_level_acl
 #- explicit_type_interface
 - extension_access_modifier
 #- fallthrough
 - fatal_error_message
 #- file_header
 ##- file_name
 #- first_where
 #- force_unwrapping
 - function_default_parameter_at_end
 - implicit_return
 #- implicitly_unwrapped_optional
 - joined_default_parameter
 - let_var_whitespace
 - literal_expression_end_indentation
 #- lower_acl_than_parent
 ##- missing_docs
 - modifier_order
 - multiline_arguments
 ##- multiline_function_chains
 ##- multiline_parameters
 - nimble_operator
 #- no_extension_access_modifier
 ##- no_grouping_extension
 - number_separator
 - object_literal
 - operator_usage_whitespace
 #- overridden_super_call
 #- override_in_extension
 #- pattern_matching_keywords
 - prefixed_toplevel_constant
 - private_action
 - private_outlet
 - prohibited_super_call
 - quick_discouraged_call
 - quick_discouraged_focused_test
 - quick_discouraged_pending_test
 - redundant_nil_coalescing
 - redundant_type_annotation
 - required_enum_case
 #- single_test_class
 - sorted_first_last
 - sorted_imports
 - strict_fileprivate
 - switch_case_on_newline
 #- trailing_closure
 #- unavailable_function
 - unneeded_parentheses_in_closure_argument
 - untyped_error_in_catch
 - vertical_parameter_alignment_on_call
 - yoda_condition

line_length:
  ignores_comments: true
  warning: 200
  error: 200
type_name:
  min_length: 3 # only warning
  max_length:   # warning and error
    warning: 50
    error: 50

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - license-validator.swift
 - precompile-tests.swift
