source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def available_pods
    pod 'MXSegmentedPager'
    pod 'M13ProgressSuite', '~> 1.2.7'
    pod 'Bohr'
    pod 'Shimmer'
    pod 'MYBlurIntroductionView'
    pod 'TTTAttributedLabel'
    pod 'Siren'
    pod 'LXReorderableCollectionViewFlowLayout', '~> 0.1.1'
end

target 'Catty' do
    available_pods
end

target 'Catty Tests' do
    available_pods
end

target 'Catty UITests' do
    available_pods
end
