source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'MXSegmentedPager', :git => 'https://github.com/maxep/MXSegmentedPager.git'
pod 'M13ProgressSuite', '~> 1.2.7'
pod 'Bohr'
pod 'AHKActionSheet'
pod 'Shimmer'
pod 'IBActionSheet'
pod 'MYBlurIntroductionView'
pod 'TTTAttributedLabel'
pod 'VGParallaxHeader', :git => 'https://github.com/stoprocent/VGParallaxHeader.git'