name: scheduled-upload-crowdin

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  CrowdinUpload:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: develop
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        working-directory: src
        bundler-cache: true
    - name: Upload Localizations to Crowdin via Fastlane
      env:
        CROWDIN_KEY: ${{ secrets.CROWDIN_API }}
      run: cd src && bundle exec fastlane ios crowdin_upload
