name: PR merged - sync Crowdin

on:
  pull_request:
    types: [closed] 

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Upload Localization to Crowdin by fastlane
      if: github.event.pull_request.merged == true
      env:
        CROWDIN_KEY: ${{ secrets.CROWDIN_API }}
      run: cd src && fastlane crowdin_upload
