name: unit-test

on:
  pull_request:

jobs:
  UnitTest:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 16
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        working-directory: src
        bundler-cache: true
    - name: Test
      run: cd src && bundle exec fastlane ios unittests
    - name: Test Report
      uses: test-summary/action@v2
      if: always()
      with:
        paths: src/fastlane/test_output/report.junit
